/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Edu' at '11/01/17 11:12' with Gradle 3.2.1
 *
 * @author Edu, @date 11/01/17 11:12
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
